#DIMITRIS BOURIS 1894 email: bourisdim@gmail.com
'''
Created on Nov 5, 2015

@author: jimbouris
'''

class Constants(object):
    AM = 1894
    MODE = "w"
    NUM_OF_PROCESSESS=3
    PROCESS1_START_ASCIIINT = 37
    PROCESS2_START_ASCIIINT = 65
    PROCESS3_START_ASCIIINT = 97
    NUMBER_OFCONNECTIONS_TOSTARTMULT = NUM_OF_PROCESSESS-1
    NUM_OFMESSAGES_PER_PROCESS = 20
    ALL_MESSAGES_INGROUP = NUM_OF_PROCESSESS * NUM_OFMESSAGES_PER_PROCESS
    MAX_ACKS = 3
